service: project-service
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    timeout: 30
    environment:
        DB_HOST: localhost
        DB_NAME: serverless-bookrenting-crud
        DB_USER: postgres
        DB_PASSWORD: password
        port: 5432

plugins:
    - serverless-prune-versions
    - serverless-esbuild
    - serverless-offline

custom:
    prune:
        automatic: true
        number: 3

functions:
    # Users functions ------------------------------------------------------------
    create:
        handler: src/handlers/users/createUser.handler
        events:
            - http:
                  path: /create-user
                  method: post
    viewUserProfile:
        handler: src/handlers/users/viewUserProfile.handler
        events:
            - http:
                path: /view-user/{id}
                method: get
    view:
        handler: src/handlers/users/viewUsers.handler
        events:
            - http:
                  path: /view-users
                  method: get

    updateUser:
        handler: src/handlers/users/updateUser.handler
        events:
            - http:
                path: /update-user/{id}
                method: patch

    deleteUser:
        handler: src/handlers/users/deleteUser.handler
        events:
            - http:
                path: /delete-user/{id}
                method: delete

    # Books functions ------------------------------------------------------------
    createBook:
        handler: src/handlers/books/createBook.handler
        events:
            - http:
                path: /create-book
                method: post
    viewBooks:
        handler: src/handlers/books/viewBooks.handler
        events:
            - http:
                path: /view-books
                method: post
    updateBook:
        handler: src/handlers/books/updateBook.handler
        events:
            - http:
                path: /update-book/{id}
                method: patch
    deleteBook:
        handler: src/handlers/books/deleteBook.handler
        events:
            - http:
                path: /delete-book/{id}
                method: delete

    # Renting functions ------------------------------------------------------------
    rentBook:
        handler: src/handlers/renting/rentBook.handler
        events:
            - http:
                path: /rent-book
                method: post
    viewRent:
        handler: src/handlers/renting/viewRent.handler
        events:
            - http:
                path: /view-rent
                method: get